import { useState } from "react";
import { Starfield } from "@/components/Starfield";
import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";
import { handleCheckout } from "@/lib/checkout";
import { useSEO } from "@/hooks/useSEO";
import "./shared.css";
import "./faq.css";

const FAQS: { q: string; a: JSX.Element }[] = [
  {
    q: "Is this report automated or AI-generated?",
    a: (
      <>
        <p>No. Every Soul Blueprint is written personally from your specific birth data. Nothing is copied from a template, nothing is generated by software. The process is deliberate and time-intensive, which is why reports are delivered within 72 hours rather than instantly.</p>
        <p>What you receive is a completely personal document written for you and only you. The depth and specificity of what arrives in your inbox is not something a system can produce. It requires a human being who understands these five systems deeply enough to hold all five simultaneously and synthesize them into a single coherent picture of one specific person.</p>
      </>
    ),
  },
  {
    q: "What if I don't know my exact birth time or location?",
    a: (
      <>
        <p>Birth time and location are required to produce a complete and accurate Soul Blueprint. Your Human Design chart, Gene Keys profile, and full Astrology chart cannot be calculated without them, and I will not produce a report that is incomplete or inaccurate. That is not something I am willing to do in good conscience.</p>
        <p>If your order comes through without a birth time or location, I will make every attempt to reach you using the contact information provided at checkout before any work begins. Your report will not be started until I have everything needed to do it correctly.</p>
        <p>Before ordering, we recommend checking your birth certificate, hospital records, or asking a family member who was present. Your exact city and country of birth is also required, not just the country. The more precise the data, the more precise the document.</p>
        <p>If you genuinely cannot locate your birth time after exhausting every option, reach out to us directly at <a href="mailto:4pointspirit@gmail.com">4pointspirit@gmail.com</a> before placing your order and we will discuss what is possible from there.</p>
      </>
    ),
  },
  {
    q: "How will I receive my report?",
    a: (
      <>
        <p>Your complete Soul Blueprint is delivered as a PDF to the email address you provide at checkout. You will receive a confirmation email immediately after your order is placed. Your report, along with your 52-Week Alignment Workbook, will follow as a separate email within 72 hours, with both documents attached.</p>
        <p>These are documents you will keep and return to. Many people read their blueprint more than once. Save it somewhere you will not lose it.</p>
      </>
    ),
  },
  {
    q: "What information do I need to provide?",
    a: (
      <>
        <p>To produce your complete Soul Blueprint, the following information is required. All of it:</p>
        <p><strong>Full legal birth name</strong>: the name on your birth certificate, including middle name. This is used for your complete Numerology profile.</p>
        <p><strong>Date of birth</strong>: day, month, and year.</p>
        <p><strong>Exact time of birth</strong>: as precise as possible. Your birth time is required for your Human Design chart, your Gene Keys profile, and your full Western and Vedic Astrology charts, including your Rising Sign and Lagna. Without it, four of the five systems cannot be calculated accurately.</p>
        <p><strong>Place of birth</strong>: your exact city and country. Not just the country. The specific city is required for precise chart calculation.</p>
        <p>There are no questionnaires or intake forms. Your birth data is the only input required; everything else is handled from there. If any required information is missing from your order, we will contact you before beginning your report.</p>
      </>
    ),
  },
  {
    q: "What is the difference between a Soul Blueprint and a regular astrology reading?",
    a: (
      <>
        <p>A standard astrology reading gives you one lens: one system, one perspective, one partial view of a complete person. A Soul Blueprint integrates five complete systems: Western Astrology, Vedic Astrology, Numerology, Human Design, and the Gene Keys. Each one sees something the others cannot. What matters is not what any single system says; it is what all five say when they are read in conversation with each other.</p>
        <p>Instead of five separate readings placed side by side, you receive one integrated narrative. A single, cohesive picture of who you are at the level beneath the roles you play and the things you have built. No single system can produce that. The synthesis is what makes a Soul Blueprint different from anything else you have encountered.</p>
      </>
    ),
  },
  {
    q: "How is this different from free readings I find online?",
    a: (
      <>
        <p>Free online readings are generated by software and applied to every person born under the same sign, number, or configuration. They describe a type. Your Soul Blueprint is written personally from your specific birth data, integrates five systems simultaneously, and is synthesized into a document that reflects you specifically.</p>
        <p>The difference is the same as between a mass-produced suit and one made precisely for your body. The raw materials may overlap. What they produce does not.</p>
      </>
    ),
  },
  {
    q: "How long does the report take to arrive?",
    a: (
      <>
        <p>Your report will arrive within 72 hours of your order. Many reports are delivered sooner, often within 24 to 48 hours, but 72 hours is the guaranteed window. This is not an automated process. Every document is written personally, and that takes the time it takes to do correctly.</p>
        <p>You will receive a confirmation email immediately after checkout. Your blueprint and workbook will follow as a separate email with both PDFs attached when they are ready.</p>
      </>
    ),
  },
  {
    q: "Can I order this as a gift?",
    a: (
      <>
        <p>Yes. The Soul Blueprint makes a profound gift for someone in a season of transition, seeking clarity, or ready to understand themselves at a deeper level. Simply include the recipient's birth information at checkout and note in the order that it is a gift, and we will include a personal note in the delivery.</p>
        <p>If you do not yet have the recipient's full birth data, reach out to us directly at <a href="mailto:4pointspirit@gmail.com">4pointspirit@gmail.com</a> and we will work with you on timing and delivery.</p>
      </>
    ),
  },
  {
    q: "What is the Couples Blueprint?",
    a: (
      <>
        <p>The Couples Blueprint includes two complete Soul Blueprints, one for each person, plus a full compatibility synthesis. The synthesis examines how your designs interact: where you amplify each other, where you create natural friction, what you are each bringing to the relationship from the level of your mechanics and your frequencies, and what you are uniquely positioned to build together.</p>
        <p>It is available for romantic partners, close friendships, and business partnerships. Understanding how two specific designs interact is one of the most clarifying things two people can do together.</p>
      </>
    ),
  },
  {
    q: "Is my birth data kept private?",
    a: (
      <>
        <p>Yes. Your birth data is used solely for the purpose of producing your Soul Blueprint and is never shared, sold, or used for any other purpose. We take the personal nature of this information seriously; it is the most intimate data you can provide, and it is treated accordingly.</p>
      </>
    ),
  },
  {
    q: "What if I have more questions before ordering?",
    a: (
      <>
        <p>Reach out directly at <a href="mailto:4pointspirit@gmail.com">4pointspirit@gmail.com</a>. Every message is read and responded to personally. There is no support queue, no automated response, no chatbot. If you have a question, you will hear from a real person.</p>
      </>
    ),
  },
];

function FAQItem({
  q,
  a,
  open,
  onToggle,
}: {
  q: string;
  a: JSX.Element;
  open: boolean;
  onToggle: () => void;
}) {
  const id = `faq-${q.slice(0, 24).replace(/\W/g, "-")}`;
  return (
    <div className={`fq-item${open ? " fq-item--open" : ""}`}>
      <button
        className="fq-question"
        onClick={onToggle}
        aria-expanded={open}
        aria-controls={id}
      >
        <span className="fq-question-text">{q}</span>
        <span className="fq-toggle" aria-hidden="true">+</span>
      </button>
      <div className="fq-answer" id={id} role="region" aria-label={q}>
        <div className="fq-answer-inner">{a}</div>
      </div>
    </div>
  );
}

export default function FAQ() {
  const [openIdx, setOpenIdx] = useState<number | null>(0);

  useSEO({
    title: "FAQ: Soul Blueprint Questions Answered | The Unified Spirit",
    description: "Answers to common questions about Soul Blueprint reports: how they work, what's included, delivery time, pricing, and the five systems: Numerology, Western Astrology, Vedic Astrology, Human Design, and Gene Keys.",
    path: "/faq",
  });

  return (
    <div className="tus-page">
      <a href="#main-content" className="skip-link">Skip to main content</a>
      <Starfield fixed />
      <Nav />

      <main id="main-content">

        {/* ── HERO ── */}
        <section className="fq-hero" aria-labelledby="faq-heading">
          <div className="fq-hero-glow" />
          <div className="fq-eyebrow">Common Questions</div>
          <h1 id="faq-heading">Everything You<br />Want to Know.</h1>
          <p>
            If your question isn't answered here, reach out directly at{" "}
            <a href="mailto:4pointspirit@gmail.com">4pointspirit@gmail.com</a>
          </p>
        </section>

        {/* ── ACCORDION ── */}
        <div className="fq-list" aria-label="Frequently asked questions">
          {FAQS.map(({ q, a }, i) => (
            <FAQItem
              key={q}
              q={q}
              a={a}
              open={openIdx === i}
              onToggle={() => setOpenIdx(openIdx === i ? null : i)}
            />
          ))}
        </div>

        {/* ── CLOSING CTA ── */}
        <div className="fq-closing">
          <div className="fq-closing-eyebrow">Still Have Questions?</div>
          <h2>We Are Here.</h2>
          <p>Reach out directly. We respond to every message personally.</p>
          <div className="fq-btn-group">
            <a href="mailto:4pointspirit@gmail.com" className="fq-btn-primary">
              ✦ &nbsp; Get In Touch
            </a>
            <button className="fq-btn-outline" onClick={() => handleCheckout("soul_blueprint")}>
              Order Your Blueprint
            </button>
          </div>
        </div>

      </main>
      <Footer />
    </div>
  );
}
