import { useEffect, useState } from "react";
import { Link } from "wouter";
import { Starfield } from "@/components/Starfield";
import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";
import { handleCheckout } from "@/lib/checkout";
import "./shared.css";
import "./faq.css";

function useFadeIn() {
  useEffect(() => {
    const els = document.querySelectorAll(".fade-in");
    const io = new IntersectionObserver(
      (entries) => entries.forEach((e) => { if (e.isIntersecting) e.target.classList.add("visible"); }),
      { threshold: 0.1 }
    );
    els.forEach((el) => io.observe(el));
    return () => io.disconnect();
  }, []);
}

const FAQS = [
  {
    q: "Is this report automated or AI-generated?",
    a: "No. Every Soul Blueprint is written by hand from your specific birth data. Nothing is copied from a template, nothing is generated by software. The process takes time — which is why reports are delivered within 24 hours rather than instantly. What you receive is a completely personal document written for you and only you.",
  },
  {
    q: "What if I don't know my exact birth time?",
    a: "You can still receive a meaningful report. Birth time is used primarily for your Ascendant (Rising Sign) in Astrology and your Human Design Type and Authority. If your birth time is unknown, we note this in your report and work with the data we do have — which still produces a deeply accurate reading. Many clients without a known birth time have described their reports as 'uncanny' and 'exactly right.' We recommend checking your birth certificate or hospital records, but it is not required to order.",
  },
  {
    q: "How will I receive my report?",
    a: "Your complete Soul Blueprint is delivered as a PDF to the email address you provide at checkout. Most reports arrive within the same day. In all cases, delivery is within 24 hours. You will have this document forever — to return to whenever you need it.",
  },
  {
    q: "What information do I need to provide?",
    a: "At checkout, you will be asked for: your full name, date of birth, time of birth (if known), and place of birth. That is everything we need to create your complete Soul Blueprint. There are no questionnaires, no intake forms, no back-and-forth. Just your birth data — and we handle everything else.",
  },
  {
    q: "What is the difference between the Soul Blueprint and a regular astrology reading?",
    a: "A standard astrology reading gives you one lens. Your Soul Blueprint integrates four complete systems — Human Design, Astrology, Numerology, and the Gene Keys — and then synthesizes them into a single cohesive document. Instead of four separate readings, you receive one complete picture of who you are at the level of your design. No single system can show you what all four show together.",
  },
  {
    q: "How is this different from free readings I find online?",
    a: "Free online readings are generated by software and applied to every person born under the same sign, number, or type. They are not personal — they are profiles. Your Soul Blueprint is written personally from your specific birth data, integrates four systems simultaneously, and is synthesized into a document that reflects you specifically. The difference is the same as between a mass-produced suit and one made precisely for your body.",
  },
  {
    q: "How long does the report take to arrive?",
    a: "Most reports are delivered the same day. In all cases, your report will arrive within 24 hours of your order. If your order is placed late in the day, it may arrive the following morning. You will receive a confirmation email immediately after checkout, and your report will follow via a separate email with your PDF attached.",
  },
  {
    q: "Can I order this as a gift?",
    a: "Absolutely. The Soul Blueprint makes an extraordinary gift for someone who is in a season of transition, seeking clarity, or ready to understand themselves more deeply. Simply include the recipient's birth information at checkout and let us know it is a gift in the notes field — we will include a personal note in the delivery.",
  },
  {
    q: "What is the Couples Blueprint?",
    a: "The Couples Blueprint includes two complete Soul Blueprints — one for each person — plus a full compatibility synthesis. This synthesis shows how your blueprints interact with each other: where you amplify each other's strengths, where you create friction, and what you are uniquely designed to build together. It is available for romantic partners, close friends, and business partnerships.",
  },
  {
    q: "Is my birth data kept private?",
    a: "Absolutely. Your birth information is used solely to create your report and is never shared, sold, or stored beyond what is necessary to deliver your blueprint. We take the privacy of your personal data seriously — it exists to serve your reading, and nothing else.",
  },
];

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className={`faq-item fade-in${open ? " open" : ""}`}>
      <button
        className="faq-q"
        onClick={() => setOpen(!open)}
        aria-expanded={open}
        aria-controls={`faq-answer-${q.slice(0, 20).replace(/\s/g, '-')}`}
      >
        <span>{q}</span>
        <span className="faq-icon" aria-hidden="true">{open ? "−" : "+"}</span>
      </button>
      <div
        className="faq-a-wrap"
        id={`faq-answer-${q.slice(0, 20).replace(/\s/g, '-')}`}
        role="region"
        aria-label={q}
      >
        <div className="faq-a">{a}</div>
      </div>
    </div>
  );
}

export default function FAQ() {
  useFadeIn();
  useEffect(() => { document.title = "FAQ — The Unified Spirit"; }, []);

  return (
    <div className="tus-page">
      <a href="#main-content" className="skip-link">Skip to main content</a>
      <Starfield fixed />
      <Nav />
      <main id="main-content">

      <section className="faq-hero" aria-labelledby="faq-heading">
        <div className="inner-sm" style={{ textAlign: "center" }}>
          <span className="tag fade-in">Common Questions</span>
          <h1 className="sec-title fade-in" id="faq-heading" style={{ fontSize: "clamp(1.8rem,5vw,3rem)", marginBottom: 20 }}>
            Everything You<br />Want to Know.
          </h1>
          <p className="sec-body fade-in" style={{ marginBottom: 0 }}>
            If your question is not answered here, reach out directly at{" "}
            <a href="mailto:4pointspirit@gmail.com" style={{ color: "var(--goldL)" }}>
              4pointspirit@gmail.com
            </a>
          </p>
        </div>
      </section>

      <div className="rule" aria-hidden="true"><span>✦</span></div>

      <section aria-label="Frequently asked questions">
        <div className="inner-sm" style={{ paddingTop: 40 }}>
          {FAQS.map(({ q, a }) => (
            <FAQItem key={q} q={q} a={a} />
          ))}
        </div>
      </section>

      <div className="rule" aria-hidden="true"><span>✦</span></div>

      <section style={{ textAlign: "center" }} aria-labelledby="faq-contact-heading">
        <div className="inner-sm">
          <span className="tag fade-in">Still Have Questions?</span>
          <h2 className="sec-title fade-in" id="faq-contact-heading">We Are Here.</h2>
          <p className="sec-body fade-in" style={{ marginBottom: 32 }}>
            Reach out directly — we respond to every message personally.
          </p>
          <div className="faq-cta-row fade-in">
            <Link href="/connect" className="hero-btn" style={{ textDecoration: "none" }}>
              ✦ &nbsp;Get In Touch
            </Link>
            <button className="outline-btn" onClick={() => handleCheckout("soul_blueprint")}>
              Order Your Blueprint
            </button>
          </div>
        </div>
      </section>

      </main>
      <Footer />
    </div>
  );
}
